# fly.toml app configuration file generated for kitchenette-server on 2024-10-30T10:46:41+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kitchenette-server'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 5280
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
